buttons:
  B:
    onPress: "CHANGE_CONTROLLER_STATUS"
    onRelease: 
  Y:
    onPress: "OPEN NIPPER"
    onRelease: "STOP NIPPER"
  A:
    onPress: "A_PRESSED"
    onRelease: "A_RELASED"
  X:
    onPress: "CLOSE NIPPER"
    onRelease: "STOP NIPPER"
  Back:
    onPress: "ARM"
    onRelease:
  Guide: 
    onPress:
    onRelease:
  Start:
    onPress:
    onRelease:
  LS:
    onPress: "TORQUE_WRIST_ON"
    onRelease: "TORQUE_WRIST_OFF"
  RS:
    onPress: "TORQUE_CLAW_ON"
    onRelease: "TORQUE_CLAW_OFF"
  LB:
    onPress: "DISARM"
    onRelease: 
  RB:
    onPress:
    onRelease:
  D-Pad-Up:
    onPress: "DPAD_UP"
    onRelease:
  D-Pad-Down:
    onPress: "DPAD_DOWN"
    onRelease:
  D-Pad-Left:
    onPress: "DPAD_LEFT"
    onRelease: 
  D-Pad-Right:
    onPress: "DPAD_RIGHT"
    onRelease:
  UPLOAD:
    onPress: "SNAP"
    onRelease:
axes:
  LSB-X: "Y"
  LSB-Y: "X"
  RSB-X: "YAW"
  RSB-Y: "Z"
  LT: "ROTATE WRIST CCW"
  RT: "ROTATE WRIST CW"
